CREATE TABLE cards (
    id TEXT,
    artist TEXT,
    asciiname TEXT,
    availability TEXT,
    bordercolor TEXT,
    cardkingdomfoilid TEXT,
    cardkingdomid TEXT,
    coloridentity TEXT,
    colorindicator TEXT,
    colors TEXT,
    convertedmanacost FLOAT,
    dueldeck TEXT,
    edhrecrank INT,
    faceconvertedmanacost FLOAT,
    facename TEXT,
    flavorname TEXT,
    flavortext TEXT,
    frameeffects TEXT,
    frameversion TEXT,
    hand TEXT,
    hasalternativedecklimit BOOLEAN,
    hascontentwarning BOOLEAN,
    hasfoil BOOLEAN,
    hasnonfoil BOOLEAN,
    isalternative BOOLEAN,
    isfullart BOOLEAN,
    isonlineonly BOOLEAN,
    isoversized BOOLEAN,
    ispromo BOOLEAN,
    isreprint BOOLEAN,
    isreserved BOOLEAN,
    isstarter BOOLEAN,
    isstoryspotlight BOOLEAN,
    istextless BOOLEAN,
    istimeshifted BOOLEAN,
    keywords TEXT,
    layout TEXT,
    leadershipskills TEXT,
    life TEXT,
    loyalty TEXT,
    manacost TEXT,
    mcmid TEXT,
    mcmmetaid TEXT,
    mtgarenaid TEXT,
    mtgjsonv4id TEXT,
    mtgofoilid TEXT,
    mtgoid TEXT,
    multiverseid INT,
    name TEXT,
    number TEXT,
    originalreleasedate DATE,
    originaltext TEXT,
    originaltype TEXT,
    otherfaceids TEXT,
    power TEXT,
    printings TEXT,
    promotypes TEXT,
    purchaseurls TEXT,
    rarity TEXT,
    scryfallid TEXT,
    scryfallillustrationid TEXT,
    scryfalloracleid TEXT,
    setcode TEXT,
    side TEXT,
    subtypes TEXT,
    supertypes TEXT,
    tcgplayerproductid TEXT,
    text TEXT,
    toughness TEXT,
    type TEXT,
    types TEXT,
    uuid TEXT,
    variations TEXT,
    watermark TEXT
);

CREATE TABLE foreign_data (
    id TEXT,
    flavortext TEXT,
    language TEXT,
    multiverseid INT,
    name TEXT,
    text TEXT,
    type TEXT,
    uuid TEXT
);

CREATE TABLE legalities (
    id TEXT,
    format TEXT,
    status TEXT,
    uuid TEXT
);

CREATE TABLE rulings (
    id TEXT,
    date DATE,
    text TEXT,
    uuid TEXT
);

CREATE TABLE set_translations (
    id TEXT,
    language TEXT,
    setcode TEXT,
    translation TEXT
);

CREATE TABLE sets (
    id TEXT,
    basesetsize INT,
    block TEXT,
    booster TEXT,
    code TEXT,
    isfoilonly BOOLEAN,
    isforeignonly BOOLEAN,
    isnonfoilonly BOOLEAN,
    isonlineonly BOOLEAN,
    ispartialpreview BOOLEAN,
    keyrunecode TEXT,
    mcmid TEXT,
    mcmidextras TEXT,
    mcmname TEXT,
    mtgocode TEXT,
    name TEXT,
    parentcode TEXT,
    releasedate DATE,
    tcgplayergroupid TEXT,
    totalsetsize INT,
    type TEXT
);
